-- Standard-Lieferpauschale für das Angebotsformular
CREATE TABLE IF NOT EXISTS delivery_fee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(19, 2) NOT NULL
);

INSERT INTO delivery_fee (name, price)
SELECT 'Lieferpauschale', 140.00
WHERE NOT EXISTS (SELECT 1 FROM delivery_fee);
